version: '2'
services:
    jhipster2-app:
        image: jhipster2
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:sqlserver://jhipster2-mssql:1433;database=tempdb
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipster2-mssql:
        extends:
            file: mssql.yml
            service: jhipster2-mssql
